/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.AuthorController;
import Controller.ConferenceController;
import Controller.PCMemberController;
import Controller.TrackController;
import Controller.ReviewController;
import Controller.PaperController;
import Controller.BestPaperAwardController;
import Controller.SubmissionController;
import DAO.DatabaseException;
import Model.AuthorModel;
import Model.ConferenceModel;
import Model.PCMemberModel;
import Model.TrackModel;
import Model.ReviewModel;
import Model.PaperModel;
import Model.BestPaperAwardModel;
import Model.SubmissionModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jialu_lin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        conferenceFrameBtn = new javax.swing.JButton();
        trackFrameBtn = new javax.swing.JButton();
        authorFrameBtn = new javax.swing.JButton();
        pcMemberFrameBtn = new javax.swing.JButton();
        reviewFrameBtn = new javax.swing.JButton();
        submissionFrameBtn = new javax.swing.JButton();
        paperFrameBtn = new javax.swing.JButton();
        bestPaperAwardFrameBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main Frame");

        conferenceFrameBtn.setText("Conference Frame");
        conferenceFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferenceFrameBtnActionPerformed(evt);
            }
        });

        trackFrameBtn.setLabel("Track Frame");
        trackFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackFrameBtnActionPerformed(evt);
            }
        });

        authorFrameBtn.setLabel("Author Frame");
        authorFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorFrameBtnActionPerformed(evt);
            }
        });

        pcMemberFrameBtn.setLabel("PC Member Frame");
        pcMemberFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcMemberFrameBtnActionPerformed(evt);
            }
        });

        reviewFrameBtn.setLabel("Review Frame");
        reviewFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewFrameBtnActionPerformed(evt);
            }
        });

        submissionFrameBtn.setLabel("Submission Frame");
        submissionFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submissionFrameBtnActionPerformed(evt);
            }
        });

        paperFrameBtn.setLabel("Paper Frame");
        paperFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperFrameBtnActionPerformed(evt);
            }
        });

        bestPaperAwardFrameBtn.setLabel("Best Paper Award Frame");
        bestPaperAwardFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestPaperAwardFrameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conferenceFrameBtn)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paperFrameBtn)
                        .addComponent(pcMemberFrameBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bestPaperAwardFrameBtn)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(trackFrameBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorFrameBtn))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(reviewFrameBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submissionFrameBtn)))
                .addGap(72, 72, 72))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conferenceFrameBtn)
                    .addComponent(trackFrameBtn)
                    .addComponent(authorFrameBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcMemberFrameBtn)
                    .addComponent(reviewFrameBtn)
                    .addComponent(submissionFrameBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bestPaperAwardFrameBtn)
                    .addComponent(paperFrameBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conferenceFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferenceFrameBtnActionPerformed
        // TODO add your handling code here:
        ConferenceFrameView my_view;
        ConferenceModel my_model;
        ConferenceController controller;
        try {
            my_view = new ConferenceFrameView();
            my_model = new ConferenceModel();
            controller = new ConferenceController(my_view, my_model);
        my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
        }
        
//        new ConferenceJFrame().setVisible(true);
    }//GEN-LAST:event_conferenceFrameBtnActionPerformed

    private void trackFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackFrameBtnActionPerformed
        TrackFrameView my_view;
        TrackModel my_model;
        TrackController controller;
        try {
            my_view = new TrackFrameView();
            my_model = new TrackModel();
        controller = new TrackController(my_view, my_model);
        my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_trackFrameBtnActionPerformed

    private void authorFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorFrameBtnActionPerformed
        AuthorFrameView my_view;
        AuthorModel my_model;
        AuthorController controller;
        try {
            my_view = new AuthorFrameView();
            my_model = new AuthorModel();
        controller = new AuthorController(my_view, my_model);
        my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_authorFrameBtnActionPerformed

    private void pcMemberFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcMemberFrameBtnActionPerformed
        PCMemberFrameView my_view;
        PCMemberModel my_model;
        PCMemberController controller;
        try {
            my_view = new PCMemberFrameView();
            my_model = new PCMemberModel();
        controller = new PCMemberController(my_view, my_model);
        my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pcMemberFrameBtnActionPerformed

    private void reviewFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewFrameBtnActionPerformed
        
        ReviewFrameView my_view;
        ReviewModel my_model;
        ReviewController controller;
        try {
            my_view = new ReviewFrameView();
            my_model = new ReviewModel();
        controller = new ReviewController(my_view, my_model);
        my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reviewFrameBtnActionPerformed

    private void submissionFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submissionFrameBtnActionPerformed
        // TODO add your handling code here:
        SubmissionFrameView my_view;
        SubmissionModel my_model;
        SubmissionController controller;
        try {
            my_view = new SubmissionFrameView();
            my_model = new SubmissionModel();
            controller = new SubmissionController(my_view, my_model);
        my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submissionFrameBtnActionPerformed

    private void paperFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperFrameBtnActionPerformed
        // TODO add your handling code here:
        PaperFrameView my_view;
        PaperModel my_model;
        PaperController controller;
        try {
            my_view = new PaperFrameView();
            my_model = new PaperModel();
            controller = new PaperController(my_view, my_model);
            my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_paperFrameBtnActionPerformed

    private void bestPaperAwardFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestPaperAwardFrameBtnActionPerformed
        // TODO add your handling code here:
        BestPaperAwardFrameView my_view;
        BestPaperAwardModel my_model;
        BestPaperAwardController controller;
        try {
            my_view = new BestPaperAwardFrameView();
            my_model = new BestPaperAwardModel();
        controller = new BestPaperAwardController(my_view, my_model);
        my_view.setVisible(true);
        } catch (DatabaseException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + "\n" + ex.getCause().getMessage(),
                                null, JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_bestPaperAwardFrameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorFrameBtn;
    private javax.swing.JButton bestPaperAwardFrameBtn;
    private javax.swing.JButton conferenceFrameBtn;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JButton paperFrameBtn;
    private javax.swing.JButton pcMemberFrameBtn;
    private javax.swing.JButton reviewFrameBtn;
    private javax.swing.JButton submissionFrameBtn;
    private javax.swing.JButton trackFrameBtn;
    // End of variables declaration//GEN-END:variables
}
